/**
 * Formal Afrikaans (af-ZA) user-facing copy for client_web2.
 * Single source of truth for labels, headings, messages, and placeholders.
 */

export const AF = {
  app: {
    title: 'Regstreekse blog — administrasie',
    brand: 'Maroela Media',
    tagline: 'Regstreekse blog',
    taglineAdmin: 'Regstreekse blog — administrasie',
    taglineLogin: 'Regstreekse blog — betroubaar, vinnig en in Afrikaans',
  },

  common: {
    loading: 'Laai…',
    loadingSession: 'Laai sessie…',
    save: 'Stoor',
    saving: 'Stoor…',
    cancel: 'Kanselleer',
    close: 'Sluit',
    remove: 'Verwyder',
    edit: 'Wysig',
    add: 'Voeg by',
    create: 'Skep',
    creating: 'Skep…',
    publish: 'Publiseer',
    unpublish: 'Ontpubliseer',
    schedule: 'Skeduleer',
    back: 'Terug',
    search: 'Soek',
    none: 'Geen',
    noneDash: '— Geen —',
    user: 'Gebruiker',
    profile: 'Profiel',
    signOut: 'Teken uit',
    signIn: 'Meld aan',
    signingIn: 'Meld tans aan…',
    understand: 'Verstaan',
    download: 'Laai af',
    filter: 'Filter',
    comingSoon: 'Binnekort beskikbaar',
    comingSoonEyebrow: 'Binnekort',
    inProgress: 'Besig',
    done: 'Voltooi',
    planned: 'Beplan',
    phaseComingSoon: 'Kom in Phase 6',
    usernamePlaceholder: 'jou.naam',
  },

  nav: {
    main: 'Hoof',
    admin: 'Administrasie',
    liveblog: 'Regstreekse blog',
    liveblogSubtitle: 'Blogs — aktief, geargiveer en verwyder',
    allBlogs: 'Alle blogs',
    active: 'Aktief',
    archived: 'Geargiveer',
    deleted: 'Verwyderde',
    general: 'Algemeen',
    instanceSettings: 'Instansie-instellings',
    integrations: 'Integrasies',
    users: 'Gebruikersbestuur',
    usersSubtitle: 'Gebruikers, rolle en toegang',
    settings: 'Liveblog-instellings',
    settingsSubtitle: 'Algemeen en instansie',
    themes: 'Temabestuur',
    themesSubtitle: 'Temas vir regstreekse blogs',
    freetypes: 'Vrye tipes',
    freetypesSubtitle: 'Pasgemaakte plasingtipes',
    advertising: 'Advertensiebestuur',
    advertisingSubtitle: 'Advertensies en versamelings',
    marketplace: 'Markplek',
    marketplaceSubtitle: 'Markplek-integrasie',
    syndication: 'Sindikasie',
    syndicationSubtitle: 'Sindikasie na eksterne stelsels',
    notifications: 'Kennisgewings',
    notificationsUnread: (n: number) => `${n} ongelees`,
    notificationsActivity: 'Aktiwiteit op jou blogs',
    notificationsEmpty: 'Alles lyk tot dusver goed.',
    closeNav: 'Sluit navigasie',
    closeMenu: 'Sluit menu',
    mainNav: 'Hoofnavigasie',
  },

  routes: {
    liveblog: 'Regstreekse blog',
    activeBlogs: 'Aktiewe blogs',
    archivedBlogs: 'Geargiveerde blogs',
    deletedBlogs: 'Verwyderde blogs',
    settings: 'Instellings',
    generalSettings: 'Algemene instellings',
    instanceSettings: 'Instansie-instellings',
    integrations: 'Integrasies',
    themes: 'Temabestuur',
    freetypes: 'Vrye tipes',
    advertising: 'Advertensiebestuur',
    marketplace: 'Markplek',
    syndication: 'Sindikasie',
    profile: 'Profiel',
    users: 'Gebruikersbestuur',
    editor: 'Blog-redigeerder',
    blogSettings: 'Blog-instellings',
    analytics: 'Blog-analise',
    defaultTitle: 'Regstreekse blog — administrasie',
  },

  ws: {
    connected: 'Gekoppel aan die kennisgewingsbediener.',
    disconnected:
      'Ontkoppeling van die kennisgewingsbediener. Probeer weer om te koppel…',
  },

  auth: {
    welcomeBack: 'Welkom terug',
    signInSubtitle: 'Meld aan by jou werkspasie',
    username: 'Gebruikersnaam',
    password: 'Wagwoord',
    forgotPassword: 'Wagwoord vergeet?',
    secureSignIn: 'Veilige aanmelding',
    secureLoginHint:
      'Gebruik die gewone aanmeldbladsy vir toegang tot Regstreekse blog.',
    resetPassword: 'Wagwoord vergeet?',
    setPassword: 'Stel jou wagwoord',
    passwordSet: 'Wagwoord gestel',
    resetEmailHint: "Ons stuur 'n herstelskakel na jou e-posadres.",
    setPasswordHint: "Kies 'n nuwe wagwoord vir jou rekening.",
    signInAvailable: 'Aanmelding is beskikbaar.',
    email: 'E-posadres',
    newPassword: 'Nuwe wagwoord',
    confirmPassword: 'Bevestig wagwoord',
    sendResetLink: 'Stuur herstelskakel',
    sending: 'Stuur…',
    setPasswordBtn: 'Stel wagwoord',
    backToSignIn: 'Terug na aanmelding',
    changePassword: 'Verander wagwoord',
    currentPassword: 'Huidige wagwoord',
    confirmNewPassword: 'Bevestig nuwe wagwoord',
    savePassword: 'Stoor wagwoord',
    passwordsMismatch: 'Wagwoorde stem nie ooreen nie.',
    passwordMinLength: 'Wagwoord moet minstens 8 karakters wees.',
    accessDenied: 'Jy het nie toestemming om hierdie bladsy te sien nie.',
    backToBlogs: 'Terug na blogs',
    changePhoto: 'Verander foto',
    uploading: 'Laai op…',
    myProfile: 'My profiel',
    loadingProfile: 'Laai profiel…',
    tabGeneral: 'Algemene inligting',
    tabGeneralShort: 'Algemeen',
    tabAuthor: 'Outeurinligting',
    tabAuthorShort: 'Outeur',
    changePasswordBtn: 'Verander wagwoord',
    passwordSection: 'Wagwoord',
    reset: 'Herstel',
    memberSince: (date: string) => `Lid sedert ${date}`,
    generalInfo: 'Algemene inligting',
    authorInfo: 'Outeurinligting',
    firstName: 'Voornaam',
    lastName: 'Van',
    phone: 'Telefoon',
    signOff: 'Aftekening',
    byline: 'Ondertitel',
    biography: 'Biografie',
    administrator: 'Administrateur',
    chooseRole: 'Kies rol…',
    emailSentTitle: 'E-pos gestuur',
    emailSentBody:
      "Indien hierdie e-posadres by ons geregistreer is, sal jy binnekort 'n skakel ontvang om jou wagwoord te stel.",
    passwordSetTitle: 'Wagwoord gestel',
    passwordSetBody: 'Jou wagwoord is gestel. Jy kan nou aanmeld.',
    goToSignIn: 'Gaan na aanmelding',
    errors: {
      invalidCredentials: 'Ongeldige gebruikersnaam of wagwoord.',
      suspended: 'Rekening is opgeskort.',
      notFound: 'Gebruiker nie gevind nie.',
      network: 'Kan nie die bediener bereik nie.',
      unknown: 'Aanmelding het misluk. Probeer asseblief weer.',
      loadProfile: 'Kon nie profiel laai nie.',
      saveProfile: 'Kon nie profiel stoor nie.',
      uploadPhoto: 'Kon nie foto oplaai nie.',
      changePassword: 'Kon nie wagwoord verander nie.',
      resetComplete: 'Kon nie wagwoordherstel voltooi nie.',
      noAccountEmail: 'Geen rekening met hierdie e-posadres nie.',
      invalidResetToken:
        "Hierdie skakel is ongeldig of het verval. Vra 'n nuwe herstel-e-pos aan.",
      accountInactive:
        'Hierdie rekening is nie aktief nie. Kontak die administrateur.',
      noUser: 'Geen gebruiker nie.',
    },
    messages: {
      profileSaved: 'Profiel gestoor.',
      photoUpdated: 'Profielfoto opgedateer.',
    },
  },

  blogs: {
    embedListTitle: 'Bloglys-embed',
    accessRequestError: 'Kon nie toegangversoek stuur nie.',
    loadThemesError: 'Kon nie temas laai nie.',
    loadUsersError: 'Kon nie gebruikers laai nie.',
    title: 'Regstreekse blogs',
    count: (n: number) => `${n} blog${n === 1 ? '' : 's'}`,
    searchPlaceholder: 'Soek blogs…',
    searchAria: 'Soek blogs',
    embedList: 'Bloglys-embed',
    embed: 'Embed',
    embedShort: 'Embed',
    createBlog: 'Skep blog',
    createModalTitle: 'Skep nuwe blog',
    titleField: 'Titel',
    description: 'Beskrywing',
    coverImage: 'Omslagbeeld',
    theme: 'Tema',
    teamMembers: 'Spanlede (opsioneel)',
    requestAccess: 'Versoek toegang',
    posts: 'Berigte',
    creator: 'Skepper',
    noBlogs: 'Geen blogs gevind nie.',
    loading: 'Laai blogs…',
    loadError: 'Kon nie blogs laai nie.',
    createError: 'Kon nie blog skep nie. Probeer asseblief weer.',
    requestAccessError: 'Kon nie versoek stuur nie.',
    embedNoUrl: 'Geen embed-URL beskikbaar nie.',
    embedLoadError: 'Kon nie embed-kode laai nie.',
    cancelSelection: 'Kanselleer',
    deleteSelected: 'Verwyder',
    deletePermanent: 'Verwyder permanent',
    prevPage: 'Vorige bladsy',
    nextPage: 'Volgende bladsy',
    pagination: 'Bloglys-bladsy',
    states: {
      active: 'Aktiewe blogs',
      archived: 'Geargiveerde blogs',
      deleted: 'Verwyderde blogs',
    },
  },

  editor: {
    backToBlogs: 'Terug na blogs',
    panels: 'Panele',
    editPanel: 'Redigeer',
    editHint: 'Nuwe plasing of wysig konsep',
    timeline: 'Tydlyn',
    timelineHint: 'Gepubliseerde plasings',
    blogNav: 'Blog-navigasie',
    analytics: 'Analise',
    blogSettings: 'Blog-instellings',
    viewLayout: 'Redigeer-uitleg',
    viewEdit: 'Redigeer',
    viewSplit: 'Verdeelde aansig',
    viewSplitShort: 'Verdeel',
    viewPreview: 'Voorskou alleen',
    viewPreviewShort: 'Voorskou',
    loadingBlog: 'Laai blog…',
    loadBlogError: 'Kon nie blog laai nie.',
    panelComingSoon: 'Kom in Phase 6',
    messages: {
      postScheduled: 'Plasing geskeduleer.',
      postPublished: 'Plasing gepubliseer.',
      postUnpublished: 'Plasing ontpubliseer.',
    },
    confirmUnpublish: 'Ontpubliseer hierdie plasing na konsepte?',
    composer: 'Plasingsamesteller',
    newPost: 'Nuwe plasing',
    editPost: 'Wysig plasing',
    editPostHint:
      'Wysig bestaande plasing. Wysigings word by stoor op die tydlyn toegepas.',
    blockTypes: 'Bloktipes',
    addBlock: (label: string) => `Voeg ${label} by`,
    removeBlock: 'Verwyder blok',
    entryTitle: 'Plasingtitel',
    entryTitlePlaceholder: 'Titel vir die regstreekse blog (opsioneel)',
    showEntryTitle: 'Gebruik as regstreekse blogtitel',
    featuredImage: {
      label: 'Hoofbeeld (nuuskaart / webhook)',
      shortLabel: 'Hoofbeeld',
      modalTitle: 'Kies hoofbeeld',
      hint: 'Kies uit bestaande beelde of laai nuwe op.',
      blogImage: 'Blog-omslagbeeld',
      blogImageMissing: 'Blog-omslagbeeld (nog nie gestel nie)',
      postImage: (n: number) => `Beeld in plasing ${n}`,
      customUpload: 'Opgeleë beeld',
      upload: 'Laai nuwe beeld op',
      uploadShort: 'Nuwe beeld',
      libraryImage: (name: string) => name,
      useBlogDefault: 'Gebruik blog-omslag',
      loading: 'Laai beelde…',
      loadError: 'Kon nie beelde laai nie',
    },
    showEntryTitleHint:
      'Wanneer geaktiveer, word hierdie titel boaan die publieke blog gewys. Die jongste plasing met hierdie opsie bepaal die titel.',
    writePost: 'Skryf jou plasing…',
    imageUrl: 'Beeld-URL',
    uploadImage: 'Laai beeld op',
    uploadingImage: 'Laai op…',
    postOptions: 'Plasing-opsies',
    unpin: 'Ontspeld',
    pin: 'Speld vas',
    removeHighlight: 'Verwyder beklemtoning',
    highlight: 'Beklemtoon',
    schedulePost: 'Skeduleer plasing',
    publishAt: 'Publiseer op',
    saveDraft: 'Stoor konsep',
    blocks: {
      text: 'Teks',
      quote: 'Aanhaling',
      image: 'Beeld',
      embed: 'Embed',
      poll: 'Meningspeiling',
      scorecard: 'Telbord',
    },
    timelineSection: 'Tydlyn',
    loadingPosts: 'Laai plasings…',
    noPosts: 'Geen plasings vir hierdie paneel nie.',
    loadMore: 'Laai meer',
    postActions: 'Plasing-aksies',
    postStatus: {
      draft: 'Konsep',
      submitted: 'Bydrae',
      scheduled: 'Geskeduleer',
    },
    noContent: '(Geen inhoud)',
    confirmDeletePost: 'Verwyder hierdie plasing?',
    errors: {
      savePost: 'Kon nie plasing stoor nie.',
      savePostDetail: (detail: string) => `Kon nie plasing stoor nie: ${detail}`,
      deletePost: 'Kon nie plasing verwyder nie.',
      publishPost: 'Kon nie plasing publiseer nie.',
      unpublishPost: 'Kon nie plasing ontpubliseer nie.',
      pinPost: 'Kon nie plasing se speldstatus wysig nie.',
      highlightPost: 'Kon nie plasing se beklemtoning wysig nie.',
    },
    preview: {
      aria: 'Lewendige blog-voorskou',
      label: 'Lewendige voorskou',
      loadingTheme: 'Laai tema…',
      themeHint: (name: string) => `Regte tema: ${name} — wysig op plasings`,
      themeHintDefault: 'Regte tema — wysig op plasings',
      device: 'Toestel',
      desktop: 'Werkskerm',
      tablet: 'Tablet',
      mobile: 'Selfoon',
      orientation: 'Orientasie',
      portrait: 'Portret',
      landscape: 'Landskap',
      openPublic: 'Openbare blog',
      openBlog: 'Maak blog oop',
      phone: 'Foon',
      themeIframe: 'Lewendige blog met tema',
    },
    draftPreview: 'Konsep-voorskou',
    draftLabel: 'Konsep — nog nie gepubliseer nie',
    draftEmpty: 'Tik inhoud om die konsep-voorskou te sien.',
    panels_config: {
      editor: 'Redigeerder',
      editorShort: 'Redigeer',
      timeline: 'Tydlyn',
      timelineShort: 'TL',
      contributions: 'Bydraes',
      scheduled: 'Geskeduleer',
      scheduledShort: 'Skedule',
      drafts: 'Konsepte',
      comments: 'Kommentare',
      ingest: 'Inname',
      ingestShort: 'Inname',
      syndication: 'Sindikasie',
    },
    freetype: {
      aria: 'Vrye tipe',
      postType: 'Plasingtipe',
      standardOption: 'Standaard (teks, embed, meningspeiling)',
      usingType: (name: string) =>
        `Hierdie plasing gebruik die vrye tipe "${name}". Jy kan die velde hieronder wysig.`,
      noFields:
        'Geen redigeerbare velde in hierdie sjabloon gevind nie. Kontroleer $veranderlikes in die vrye tipe-sjabloon.',
      loading: 'Laai vrye tipes…',
      htmlPlaceholder: 'HTML- of embed-kode',
    },
    richText: {
      toolbar: 'Teksformatering',
      font: 'Lettertipe',
      style: 'Styl',
      bold: 'Vet',
      italic: 'Skuins',
      underline: 'Onderstreep',
      h2: 'Opskrif 2',
      h3: 'Opskrif 3',
      paragraph: 'Paragraaf',
      paragraphGroup: 'Paragraaf',
      bulletList: 'Bulletlys',
      numberedList: 'Genommerde lys',
      quote: 'Aanhaling',
      align: 'Belyn',
      left: 'Links',
      center: 'Middel',
      right: 'Regs',
      justify: 'Belyn beide kante',
      edit: 'Bewerk',
      link: 'Skakel',
      unlink: 'Verwyder skakel',
      clearFormat: 'Vee formatering uit',
      history: 'Geskiedenis',
      undo: 'Ontdoen',
      redo: 'Herdoen',
      linkUrlPrompt: 'Voer URL in',
    },
    poll: {
      question: 'Vraag',
      questionPlaceholder: 'Meningspeiling-vraag',
      answers: 'Antwoorde',
      answerN: (n: number) => `Antwoord ${n}`,
      addAnswer: '+ Antwoord',
      days: 'Dae',
      hours: 'Ure',
      minutes: 'Minute',
    },
    embed: {
      loading: 'Laai embed…',
      loadingX: 'Laai X-embed…',
      loadError: 'Kon nie embed laai nie.',
      previewBuildError:
        'Kon nie \'n voorbeskou bou nie. Gaan die URL na of probeer weer.',
      iframelyLoadError: 'Kon nie Iframely embed.js laai nie',
      urlOrCodeLabel: 'URL of embed-kode',
      urlPlaceholder: 'https:// of plak embed-HTML',
      urlHint: 'Plak of tik \'n skakel — die embed word outomaties opgelos.',
      changeUrl: 'Verander URL',
      providers: {
        twitter: 'X (Twitter)',
        facebook: 'Facebook',
        instagram: 'Instagram',
        picture: 'Beeld',
        generic: 'Embed',
      },
    },
    tags: {
      label: 'Etikette',
      loading: 'Laai etikette…',
      noneGlobal:
        'Geen globale etikette nie. Voeg etikette by onder Instellings → Algemeen.',
      noneSelected: 'Geen etikette gekies nie.',
      remove: (tag: string) => `Verwyder ${tag}`,
    },
    settings: {
      tabsAria: 'Instelling-oortjies',
      status: 'Blog-status',
      title: 'Titel',
      description: 'Beskrywing',
      blogImage: 'Blog-beeld',
      theme: 'Tema',
      language: 'Taal',
      embedHeight: 'Embed-hoogte',
      embedCode: 'Embed-kode',
      category: 'Kategorie',
      categoryNone: '— Geen —',
      allowComments: 'Gebruikers kan kommentaar lewer',
      postLimit: 'Plasing-limiet',
      blogId: 'Blog-ID',
      team: 'Span',
      editTeam: 'Wysig span',
      noMembers: 'Geen spanlede nie',
      saveTeam: 'Stoor span',
      outputs: 'Uitsette',
      noOutputs: 'Geen uitsetkanale nie',
      consumers: 'Verbruikers',
      saveTags: 'Stoor etikette',
      tagsPlaceholder: 'sport, nuus',
      loadingBlog: 'Laai blog-instellings…',
      backToEditor: 'Terug na redigeerder',
      confirmDeleteOutput: 'Verwyder hierdie uitsetkanaal?',
      uploadCover: 'Laai beeld op',
      noRestriction: 'Geen beperking',
      saved: 'Instellings gestoor.',
      outputRemoved: 'Uitset verwyder.',
      errors: {
        save: 'Kon nie instellings stoor nie.',
        deleteOutput: 'Kon nie uitset verwyder nie.',
      },
    },
    scorecard: {
      name: 'Telbord',
      ariaLabel: 'Telbord',
      hint: 'Vul die wedstryd in — die kaart hieronder is presies hoe lesers dit op die blog sal sien.',
      rememberLast: 'Onthou laaste telbord',
      matchType: 'Tipe wedstryd',
      cricketHint:
        'Krieket: telling onder elke span (bv. 245/8). Stel Huidige oor en kies watter span kolf — kolwers verskyn by die kolfspan, boulers by die ander kant.',
      currentOver: 'Huidige oor',
      battingSide: 'Kolfspan',
      homeBatting: 'Tuisspan kolf',
      awayBatting: 'Wegspan kolf',
      scorersHeading: 'Opskrif spelerslys',
      bowlersHeading: 'Opskrif boulers',
      detailColumnLabel: 'Etiket detailkolom',
      homeTeam: 'Tuisspan',
      awayTeam: 'Wegspan',
      showOnCard: 'Wys op kaart',
      teamName: 'Spannaam',
      teamNamePlaceholder: 'bv. Springbokke',
      score: 'Telling',
      scorePlaceholderCricket: 'bv. 245/8',
      teamLogo: 'Spanlogo',
      teamStats: 'Spanstatistieke',
      labelField: 'Etiket',
      labelPlaceholder: 'bv. Boulbeurte',
      valueField: 'Waarde',
      valuePlaceholder: 'bv. 50,2',
      statField: 'Stat.',
      runsPlaceholder: 'Lopies',
      playerField: 'Speler',
      playerNamePlaceholder: 'Spelernaam',
      figuresField: 'Syfers',
      figuresPlaceholder: 'bv. 4/32',
      bowlerField: 'Bouler',
      bowlerNamePlaceholder: 'Boulernaam',
      matchStatusCricket: 'Wedstrydstatus',
      matchStatusRugby: 'Rust / kwartiertelling',
      matchStatusPlaceholderCricket: 'bv. 2de beurt · Dag 3',
      matchStatusPlaceholderRugby: 'bv. HT 1–0 of FINALE',
      matchInfo: 'Wedstrydinligting',
      matchInfoPlaceholder: 'bv. Loftus Versfeld · 72 000 toeskouers',
      backgroundOptional: 'Agtergrondbeeld (opsioneel)',
      uploadLogo: 'Laai spanlogo op',
      uploadBackground: 'Laai agtergrond op',
      removeStat: 'Verwyder statistiek',
      removePlayer: 'Verwyder speler',
      removeBowler: 'Verwyder bouler',
      scoreAria: (home: string, away: string) => `Telling ${home} teen ${away}`,
      sideDisplay: {
        auto: 'Outo (volg kolfspan)',
        batters: 'Kolwers',
        bowlers: 'Boulers',
        both: 'Beide',
        none: 'Versteek op die kaart',
      },
      presets: {
        rugby: 'Rugby',
        cricket: 'Krieket',
        custom: 'Pasgemaak',
        goalScorers: 'Doelskoppe',
        batters: 'Kolwers',
        bowlers: 'Boulers',
        minute: 'Min.',
        overs: "O.",
        stat: 'Stat.',
        players: 'Spelers',
      },
    },
    output: {
      edit: 'Wysig uitsetkanaal',
      new: 'Nuwe uitsetkanaal',
      name: 'Naam',
      theme: 'Tema',
      collection: 'Versameling',
      embed: 'Embed',
      embedCode: 'Embed-kode',
      embedCodeFor: (name: string) => `Embed-kode: ${name}`,
      noPublicUrl:
        'Geen publieke URL vir hierdie uitset nog nie. Publiseer die blog om embed-URL\'s te kry.',
    },
  },

  settings: {
    loading: 'Laai instellings…',
    loadingInstance: 'Laai instansie-instellings…',
    defaultTheme: 'Verstek tema',
    youtubePrivacy: 'YouTube-privaatheid',
    quotationMarks: 'Aanhalingstekens (taal)',
    embedHeightResponsive: 'Verstek embed-hoogte responsief',
    globalTags: 'Globale etikette',
    blogCategories: 'Blog-kategorieë',
    tagPlaceholder: "Voer 'n etiket in",
    categoryPlaceholder: "Voer 'n kategorie in",
    tagHint:
      "Druk Enter of klik Voeg by. Om 'n bestaande etiket te wysig, verander nie etikette op plasings nie — verwyder en voeg weer by.",
    categoryHint:
      'Kategorieë verskyn in die blog-instellings keuselys. Druk Enter of klik Voeg by.',
    instanceJson: 'Instansie-JSON',
    privacy: {
      private: 'Privaat',
      public: 'Publiek',
      unlisted: 'Nie gelys nie',
    },
    languages: {
      af: 'Afrikaans',
      en: 'Engels',
      de: 'Duits',
    },
    saveSuccess: 'Instellings suksesvol gestoor.',
    instanceSaveSuccess: 'Instansie-instellings suksesvol gestoor.',
    errors: {
      load: 'Kon nie instellings laai nie.',
      save: 'Kon nie instellings stoor nie. Probeer later weer.',
      loadInstance: 'Kon nie instansie-instellings laai nie.',
      saveInstance: 'Kon nie instansie-instellings stoor nie.',
    },
  },

  themes: {
    loading: 'Laai temas…',
    loadingOptions: 'Laai opsies…',
    noBlogs: 'Geen blogs gebruik hierdie tema nie.',
    backToBlogs: 'Terug na blogs',
    uploadTheme: 'Laai tema op',
    confirmDelete: (name: string) => `Verwyder tema "${name}"?`,
    errors: {
      load: 'Kon nie temas laai nie.',
      loadSettings: 'Kon nie tema-instellings laai nie.',
      saveSettings: 'Kon nie instellings stoor nie.',
    },
  },

  users: {
    email: 'E-pos',
    sendPasswordReset: 'Stuur wagwoordherstel',
    loading: 'Laai gebruikers…',
    pageSubtitle:
      'Skep, wysig, deaktiveer en heraktiveer Liveblog-gebruikers.',
    noUsersFound: 'Geen gebruikers gevind nie.',
    searchPlaceholder: 'Soek op naam, gebruikersnaam of e-pos…',
    searchAria: 'Soek gebruikers',
    username: 'Gebruikersnaam',
    newUser: 'Nuwe gebruiker',
    editUser: (name: string) => `Wysig: ${name}`,
    role: 'Rol',
    status: {
      deactivated: 'Gedeaktiveer',
      inactive: 'Onaktief',
      active: 'Aktief',
    },
    errors: {
      load: 'Kon nie gebruikers laai nie.',
      loadOne: 'Kon nie gebruiker laai nie.',
      save: 'Kon nie stoor nie.',
      status: 'Kon nie status wysig nie.',
      deactivate: 'Kon nie gebruiker deaktiveer nie.',
      reactivate: 'Kon nie gebruiker heraktiveer nie.',
      noChanges: 'Geen veranderinge om te stoor nie.',
    },
  },

  analytics: {
    title: 'Blog-analise',
    missingId: 'Blog-ID ontbreek.',
    loading: 'Laai analise…',
    exportCsv: 'Laai CSV af',
    backToEditor: 'Terug na redigeerder',
    filterPlaceholder: 'Filter volgens verwysende URL…',
    noData: 'Geen analise-data nie.',
    done: 'Klaar',
    errors: {
      load: 'Kon nie analise laai nie.',
    },
  },

  freetypes: {
    builtinScorecardName: 'Telbord',
    standardOptionShort: 'Standaard (teks / embed / poll)',
    none: 'Geen vrye tipes nie.',
    edit: 'Wysig vrye tipe',
    new: 'Nuwe vrye tipe',
    name: 'Naam',
    template: 'Sjabloon ($veranderlikes verplig)',
    errors: {
      load: 'Kon nie vrye tipes laai nie.',
      save: 'Kon nie stoor nie.',
      delete: 'Kon nie verwyder nie.',
    },
    confirmDelete: (name: string) => `Verwyder vrye tipe "${name}"?`,
    validation: {
      templateVars: 'Sjabloon moet minstens een $veranderlike bevat.',
      uniqueName: 'Vrye tipe name moet uniek wees.',
    },
    messages: {
      updated: 'Vrye tipe opgedateer.',
      created: 'Vrye tipe geskep.',
      removed: 'Vrye tipe verwyder.',
    },
  },

  advertising: {
    newAd: 'Nuwe advertensie',
    editAd: 'Wysig advertensie',
    newCollection: 'Nuwe versameling',
    editCollection: 'Wysig versameling',
    name: 'Naam',
    type: 'Tipe',
    htmlText: 'HTML-teks',
    errors: {
      load: 'Kon nie advertensies laai nie.',
    },
    confirmDeleteAd: (name: string) => `Verwyder "${name}"?`,
    confirmDeleteCollection: (name: string) => `Verwyder versameling "${name}"?`,
  },

  integrations: {
    title: 'Integrasies',
    subtitle: 'Koppel regstreekse blogs aan eksterne stelsels via webhooks.',
    errors: {
      load: 'Kon nie integrasies laai nie.',
      save: 'Kon nie webhook stoor nie.',
      remove: 'Kon nie webhook verwyder nie.',
      test: 'Kon nie webhook toets nie.',
    },
    webhooks: {
      heading: 'Webhooks',
      description:
        'Stuur HTTP-versoeke wanneer gebeure in blogs plaasvind. Kies die blog en dataformaat vir die ontvanger.',
      add: 'Nuwe webhook',
      addTitle: 'Skep webhook',
      editTitle: 'Wysig webhook',
      empty: 'Geen webhooks is nog opgestel nie.',
      saved: 'Webhook gestoor.',
      removed: 'Webhook verwyder.',
      test: 'Toets',
      testing: 'Besig…',
      testQueued: (postId: string) =>
        `Webhook-toets is in die ry geplaas (laaste plasing: ${postId}).`,
      disabled: 'Gedeaktiveer',
      allBlogs: 'Alle blogs',
      newsCardHint:
        'Stuur WP GraphQL-versoenbare nuuskaart-data (posts.nodes) vir kenmerkkaarte.',
      fields: {
        name: 'Naam',
        destination: 'Bestemmings-URL',
        destinationHint:
          'http:// word outomaties bygevoeg. Gebruik 127.0.0.1:3000/... of jou IP — in Docker word localhost outomaties na host.docker.internal herlei.',
        action: 'Aksie',
        blog: 'Blog',
        dataFormat: 'Dataformaat',
        enabled: 'Aktief',
      },
      actions: {
        post_created: 'Nuwe plasing gepubliseer',
        post_updated: 'Plasing opgedateer',
        post_deleted: 'Plasing verwyder',
      },
      dataFormats: {
        news_card: 'Nuuskaart (WP GraphQL)',
        raw: 'Rou Liveblog-data',
      },
    },
  },

  marketplace: {
    noBlogs: 'Geen blogs nie.',
    noUpcoming: 'Geen komende blogs nie.',
    embed: 'Embed',
    embedCode: 'Embed-kode',
    embedModalTitle: 'Embed-kode',
    embedModalBody: (title: string) =>
      `Embed vir ${title} — volledige voorbeeld volg in Phase 6+.`,
    errors: {
      load: 'Kon nie markplek laai nie.',
    },
  },

  syndication: {
    newProducer: 'Nuwe produseerder-naam',
    noConsumers: 'Geen verbruikers nie.',
    errors: {
      load: 'Kon nie sindikasie laai nie.',
    },
    confirmDeleteProducer: (name: string) => `Verwyder produseerder "${name}"?`,
    messages: {
      producerCreated: 'Produseerder geskep.',
      producerRemoved: 'Produseerder verwyder.',
    },
  },

  notifications: {
    errors: {
      load: 'Kon nie kennisgewings laai nie.',
    },
  },

  upload: {
    noUploadId: 'Geen upload-ID teruggekry nie',
    imageTooLarge: (maxMb: number) => `Beeld is groter as ${maxMb} MB`,
  },

  placeholder: {
    defaultDescription: 'Hierdie afdeling word in ’n volgende fase geïmplementeer.',
    trackingNote:
      'Navigasie en dop is reeds bedraad — inhoud volg per mechanism README in',
  },

  setup: {
    title: 'Web2-kliëntopstelling',
    description:
      'Groenveld-modernisering van die Liveblog-adminportaal. Dit vervang die legacy AngularJS-kliënt met React 19, Vite 6 en Tailwind CSS 4 — dieselfde strategie as',
    modernStack: 'Moderne stapel',
    modernStackDesc: 'Vite · React 19 · TypeScript · TanStack Query · React Router 7',
    trackedMigration: 'Gedokumenteerde migrasie',
    trackedMigrationDesc: 'Planne in plans/mechanisms/ met gefaseerde take en riglyne.',
    devPort: 'Ontwikkelingspoort 9000',
    devPortDesc: 'API word via Vite na :5000 deurgebondel.',
    roadmap: 'Padkaart',
    phases: 'Implementasiefases',
    phasesSubtitle: 'Gedokumenteer in client_web2/plans/',
    quickStart: 'Vinnige begin',
    quickStartSubtitle: 'Plaaslike ontwikkeling',
    openLegacy: 'Open legacy-admin (:9000)',
    testApi: 'Toets API-deurverbinding',
    phaseLabels: {
      setup: 'Opstelling',
      shellAuth: 'Raamwerk + aanmelding',
      blogList: 'Bloglys',
      editor: 'Redigeerder',
    },
    phaseStatus: {
      active: 'Aktief',
      done: 'Voltooi',
      upcoming: 'Komend',
    },
  },
} as const;

/** Login error codes → formal Afrikaans messages */
export const AF_LOGIN_ERRORS: Record<string, string> = {
  '401': AF.auth.errors.invalidCredentials,
  '403': AF.auth.errors.suspended,
  '404': AF.auth.errors.notFound,
  network: AF.auth.errors.network,
  unknown: AF.auth.errors.unknown,
};
